version: "2.4"

services:
  app:
    container_name: llm-benchmark-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379
      - DATABASE_NAME=llm_benchmark
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - llm-network

  mongo:
    container_name: llm-benchmark-mongo
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - llm-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: llm-benchmark-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - llm-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  llm-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local