version: "3.8"

services:
  app:
    container_name: llm-benchmark-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mongodb+srv://llm-db-dev:SaSZjXu4L3LcuVTK@llmcluster.begfk.mongodb.net/?retryWrites=true&w=majority&appName=LLMCLUSTER"
      - DATABASE_NAME=llm_benchmark
   
    networks:
      - llm-network

networks:
  llm-network:
    driver: bridge

