version: "3.8"

services:
  app:
    container_name: llm-benchmark-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    networks:
      - llm-network

  mongo:
    container_name: llm-benchmark-mongo
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - llm-network

  redis:
    container_name: llm-benchmark-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - llm-network

networks:
  llm-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local