replicaCount: 1

image:
  repository: tochinwachukwu/llm-benchmark
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: llm-benchmark.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"

nodeSelector: {}
tolerations: []
affinity: {}

database:
  url: "mongodb://mongo:27017"
  name: "llm_benchmark"

mongodb:
  enabled: true
  image: mongo:5.0
  port: 27017
  servicePort: 27017
  resources: {}
  url: "mongodb://mongo:27017"
  name: "llm_benchmark"

redis:
  enabled: true
  image: redis:6.0
  port: 6379
  servicePort: 6379
  resources: {}
  url: "redis://redis:6379"
