apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llm-benchmark.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "llm-benchmark.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "llm-benchmark.name" . }}
    spec:
      containers:
        - name: fastapi
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URL
              value: {{ .Values.mongodb.url }}
            - name: REDIS_URL
              value: {{ .Values.redis.url }}
          resources: 
            {{- toYaml .Values.resources | nindent 12 }}