apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-benchmark.fullname" . }}-redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.servicePort }}
      targetPort: {{ .Values.redis.port }}
  selector:
    app: {{ include "llm-benchmark.name" . }}-redis